# Generated by Django 3.0.7 on 2020-06-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200630_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('environment', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='bird',
            name='locations',
            field=models.ManyToManyField(to='main_app.Location'),
        ),
    ]
