# Generated by Django 3.0.7 on 2020-07-05 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200630_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='environment',
            new_name='address',
        ),
    ]
